name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Geheimes Secret verwenden
        run: echo "Mein geheimes Secret ist ${{ secrets.MEIN_GEHEIMNIS }}"
